name: Test Python Tk
on:
  push:
    branches:
      - test-649
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13, macos-latest-large, macos-15-large]
        # python-version: ["3.8.18", "3.9.21", "3.10.16"]
        python-version: ["3.8", "3.9", "3.10"]

      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        # uses: priya-kinthali/setup-python@test-tcltk
        with:
          python-version: ${{ matrix.python-version }}
      - name: Verify Python Tk Version
        run: |
          python -c "import tkinter; print(f'Tkinter TkVersion: {tkinter.TkVersion}')"
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Run tk script (closes itself after 5 seconds) - Ubuntu
        if: runner.os == 'Linux'
        run: xvfb-run python tk_min.py
      - name: Run tk script (closes itself after 5 seconds)
        if: runner.os != 'Linux'
        run: python tk_min.py
        #test
