name: Test 1071

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ubuntu-latest
    name: Set up Python on Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Verify Python installation
        run: pip install -r requirements.txt
      - name: Verify Python version
        run: python --version
